spring:
  application:
    name: vbuynet-service-consumer-site
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.1:8848




server:
  port: 9504



management:
  endpoints:
    web:
      exposure:
        include: "*"